version: '3'
services:
  dev-server:
    build: ./
    ports:
      - '4040:4040'
    links:
      - ganache
    environment:
      ganache: 'ganache:8545'
  ganache:
    image: 'trufflesuite/ganache-cli:v6.12.2'
    ports:
      - '8545:8545'
    command: -l 8000000 --networkId 1576478390085 --deterministic --hostname=0.0.0.0
  mainnet-fork:
    image: 'trufflesuite/ganache-cli:v6.12.2'
    ports:
      - '8546:8545'
    command: -l 8000000 --deterministic --hostname=0.0.0.0 --chainId 1 --fork https://mainnet.infura.io/v3/d119148113c047ca90f0311ed729c466
  ipfs:
    image: 'ipfs/go-ipfs:v0.4.23'
    ports:
      - '5001:5001'
      - '8080:8080'
      - '4001:4001'
